[package]
name = "falcon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "falcon-bench"
path = "src/main.rs"

[[bench]]
name = "falcon_divan"
harness = false

[dependencies]
pqcrypto-falcon = "0.4.1"
pqcrypto-traits = "0.3"

[dev-dependencies]
divan = "0.1"
