[package]
name = "hss"
version.workspace = true
edition.workspace = true

[dependencies]
hbs-lms = "0.2.0-alpha.1"

[dev-dependencies]
divan = "0.1"

[[bin]]
name = "hss-bench"
path = "src/main.rs"

[[bench]]
name = "hss_divan"
harness = false
